<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Malar</title>
</head>
<body>
<h1>hello {{ $data['first_name'] }} {{ $data['last_name'] }}</h1>
<h5>{{ $data['mobile'] }}</h5>
    <p>Your account is under review
Within 48 hours to 72 hours exposed </p>
<p>Ihr Konto wird überprüft
Innerhalb von 48 Stunden bis 72 Stunden ausgesetzt</p>
</body>
</html> 